misc_tools/urls.py
from django.urls import path, include, re_path
from . import views

app_name = "misc_tools"


urlpatterns = [
    path("ajax/get_colonias/", views.get_colonias, name="get_colonias"),
]

project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

misc_tools/models.py
from django.db import models

ENTIDADES = (
    (1, "AGU", "Aguascalientes"),
    (2, "BCN", "Baja California"),
    (3, "BCS", "Baja California Sur"),
    (4, "CAM", "Campeche"),
    (5, "CHP", "Chiapas"),
    (6, "CHH", "Chihuahua"),
    (7, "COA", "Coahuila"),
    (8, "COL", "Colima"),
    (9, "DIF", "Ciudad de México"),
    (10, "DUR", "Durango"),
    (11, "GUA", "Guanajuato"),
    (12, "GRO", "Guerrero"),
    (13, "HID", "Hidalgo"),
    (14, "JAL", "Jalisco"),
    (15, "MEX", "Estado de México"),
    (16, "MIC", "Michoacán"),
    (17, "MOR", "Morelos"),
    (18, "NAY", "Nayarit"),
    (19, "NLE", "Nuevo León"),
    (20, "OAX", "Oaxaca"),
    (21, "PUE", "Puebla"),
    (22, "QUE", "Querétaro"),
    (23, "ROO", "Quintana Roo"),
    (24, "SLP", "San Luis Potosí"),
    (25, "SIN", "Sinaloa"),
    (26, "SON", "Sonora"),
    (27, "TAB", "Tabasco"),
    (28, "TAM", "Tamaulipas"),
    (29, "TLA", "Tlaxcala"),
    (30, "VER", "Veracruz"),
    (31, "YUC", "Yucatán"),
    (32, "ZAC", "Zacatecas"),
)

class Direccion(models.Model):
    municipio = models.CharField(max_length=255, null=False, blank=True, default="")
    localidad = models.CharField(max_length=255, null=False, blank=True, default="")
    estado = models.CharField(max_length=255, blank=True, default="")
    calle = models.CharField(max_length=500, null=True, blank=True, default="")
    colonia = models.CharField(max_length=100, null=True, blank=True, default="")
    cp = models.CharField(max_length=7, null=True, blank=True, default="")
    telefono = models.CharField(max_length=100, null=True, blank=True, default="")
    email = models.EmailField(blank=True, default="")
    numero_e = models.CharField(max_length=100, blank=True, null=False, default="")
    numero_i = models.CharField(max_length=100, blank=True, null=False, default="")
    pais_residencia = models.CharField(max_length=3, default="")
    
    # https://stackoverflow.com/questions/12504208/what-mysql-data-type-should-be-used-for-latitude-longitude-with-8-decimal-places
    latitud = models.DecimalField(max_digits=11, decimal_places=8, default=0, blank=True, null=True)
    longitud = models.DecimalField(max_digits=11, decimal_places=8, default=0, blank=True, null=True)
    referencia = models.CharField(max_length=500, null=True, blank=True, default="")
    
    #CLAVES PARA COMERCIO EXTERIOR
    ce_municipio = models.CharField(max_length=3, null=True, blank=True, default="")
    ce_localidad = models.CharField(max_length=3, null=True, blank=True, default="")
    ce_estado = models.CharField(max_length=3, blank=True, default="")
    ce_colonia = models.CharField(max_length=4, null=True, blank=True, default="")

    def __str__(self):
        d = self.calle
        if self.numero_e:
            d += " N° %s" % self.numero_e
        
        if self.numero_i:
            d += "-%s" % self.numero_i
        
        if not d:
          return ""
        return d


    def set_latlng(self, api_key=None):
      import requests

      if self.latitud and self.longitud:
        return False

      if not api_key:
        from admintotal.models import ConfiguracionGeneral

        api_key = ConfiguracionGeneral.objects.values_list(
            'google_api_key', 
            flat=True
        ).first()

        if not api_key:
          api_key = settings.AT_MAPS_KEY

      try:
          r = requests.get(
              'https://maps.googleapis.com/maps/api/geocode/json', 
              params={
                'key': api_key,
                'address': self.get_address_for_google_maps()
              },
              timeout=5,
          )

          if hasattr(r, 'json'):
              res = r.json()
              if res['status'] == 'OK' and 'results' in res:
                  first_result = res['results'].pop(0)
                  self.latitud = first_result['geometry']['location']['lat']
                  self.longitud = first_result['geometry']['location']['lng']
                  self.save()
                  return True
                  
          return False

      except requests.exceptions.Timeout:
          return False
      
      except requests.exceptions.RequestException:
          return False
      
      return False

    def to_dict(self, compacta=False):
      if not self.id:
        return {}

      if compacta:
        return {
          'id': self.id,
          'telefono': self.telefono,
          'email': self.email,
          'direccion_completa': self.direccion_corta(),
          'lat': str(self.latitud) if self.latitud else 0,
          'lng': str(self.longitud) if self.longitud else 0,
        }

      return {
        'id': self.id,
        'municipio': self.municipio,
        'localidad': self.localidad,
        'estado': self.estado,
        'calle': self.calle,
        'colonia': self.colonia,
        'cp': self.cp,
        'telefono': self.telefono,
        'email': self.email,
        'numero_e': self.numero_e,
        'numero_i': self.numero_i,
        'pais_residencia': self.pais_residencia,
        'direccion_completa': self.direccion_corta(),
        'lat': str(self.latitud) if self.latitud else 0,
        'lng': str(self.longitud) if self.longitud else 0,
      }

    def get_address_for_google_maps(self):
      if not self.cp:
        return ''
        
      return ' '.join([
          self.calle,
          self.numero_e,
          self.colonia,
          self.cp,
          self.localidad + ',',
          self.estado
      ])
    
    def get_maps_link(self):
        if self.latitud:
            return "https://maps.google.com/maps?q=%s,%s" % (
                self.latitud,
                self.longitud
            )

        return "https://maps.google.com/maps?q=%s" % (self.direccion_corta())

    def colonia_ciudad(self):
        out = ""
        if self.colonia:
            out += ' Col. %s' % self.colonia
            
        if self.cp:
            out += ' C.P. %s' % self.cp
            
        if self.municipio:
            out += ' %s' % self.municipio
        
        if self.estado:
            out += ' %s' % self.estado
        return out
    #pais = CountryField()
    
    def ciudad(self):
        return Foo(c=self.municipio, e=self.estado)
    
    def ciudad_delegacion(self) :
        if self.estado == "MEXICO DF":
            return "Delegación"
        return "Ciudad"
    
    def complete(self, completa=True):
        out = self.calle
        
        if self.numero_e:
            out += ' N° %s' % self.numero_e
            if self.numero_i:
                out += '-%s' % self.numero_i
        
        if self.colonia > '':
            out += u' Col. %s' % self.colonia
            
        if self.cp and self.cp > '':
            out += ' C.P. %s' % self.cp
            
        if self.municipio:
            out += u' %s,' % self.municipio
        
        if self.estado:
            out += u' %s.' % self.estado
        
        if completa:
            if self.telefono:
                out += ' Tel %s' % self.telefono
                
            if self.email:
                out += ' ' + self.email
                
        return out

    def direccion_corta(self, completa=True):
        return self.complete(completa=False)
        
    def direccion_larga(self):
        out = self.calle + " " + self.numero_e + " " + self.numero_i
        
        out += "<div>" 
        if self.colonia:
            out += 'Col. %s' % self.colonia
        
        if self.cp:
            out += ' C.P. %s' % self.cp
        out += "</div><div>"

        if self.municipio:
            out += '%s,' % self.municipio
        
        if self.estado:
            out += ' %s.' % self.estado
        out += "</div><div>"
        if self.telefono:
            out += 'Tel: %s' % self.telefono
        out += "</div>"
            
        return mark_safe(out)

    
    def get_clave_estado(self):
        from .functions import reemplazar_acentos
        if self.estado.lower() == "distrito federal":
          return "DIF"

        if self.estado.upper() == "MÉXICO" or self.estado.lower() == "méxico" or self.estado.lower() == "mexico":
          return "MEX"

        estado = self.estado.lower()
        for entidad in ENTIDADES:
            entidad_catalogo = entidad[2].lower()
            if entidad_catalogo in estado or  reemplazar_acentos(entidad_catalogo) in estado:
                return entidad[1]
        return self.estado.upper()


    def get_direccion_geoc(self):
        return "%s %s, %s, %s %s, %s" % (self.calle, self.numero_e, self.colonia, self.cp, self.municipio, self.estado)
    
    def show_ciudad(self):
        return "%s, %s" % (self.municipio, self.estado)
   
    def save(self, *args, **kwargs):
        if self.colonia:
          self.colonia = self.colonia.strip()
          
        if self.calle:
          self.calle = self.calle.strip()
          
        if self.municipio:
          self.municipio = self.municipio.strip()
          
        if self.localidad:
          self.localidad = self.localidad.strip()
          
        if self.estado:
          self.estado = self.estado.strip()
          
        return super(Direccion, self).save(*args, **kwargs)

misc_tools/views.py
from django.shortcuts import render
from .functions import json_response
from django.conf import settings
import requests

def get_colonias(request):
    """
    Regresa un  listado de colonias a partir de un código postal.
    """
    cp = request.GET.get("cp")

    if not cp:
        return json_response({
            "status": "error",
            "message": "El parámetro GET cp no fué especificado"
        })

    try:
        url = settings.UBICACIONES_URL.format(cp=cp)
        return json_response(requests.get(url).json())
    except Exception as e:
        #send_to_sentry(e)
        return json_response({
            "status": "error",
            "message": "Hubo un error al consultar la información."
        })

misc_tools/templates/misc_tools/custom_file_input.html
{% load thumbnail %}
<script>
function toggle_{{ widget.name }}(inputName) {
	var divElement = document.querySelector(".input-update-"+inputName)
	var hidden = true
	if (window.getComputedStyle(divElement).display === "none") {
		hidden = false
	}
	divElement.style = hidden ? "display:none" : "";
};
</script>

<div>
	{% if widget.is_initial %}
		{% thumbnail widget.value "x90" format="PNG" as im %}
		<div>
			<a href="{{ widget.value.url }}">
		    	<img src="{{ im.url }}"  class="img-fluid img-thumbnail">
			</a>
		</div>
	    {% endthumbnail %}
			
		{% if not widget.required %}
		<div class="d-inline-block mr-1">
			<label for="{{ widget.checkbox_id }}">
				<input type="checkbox" name="{{ widget.checkbox_name }}" id="{{ widget.checkbox_id }}">
				{{ widget.clear_checkbox_label }}
			</label>
		</div>
		{% endif %}
		<div class="d-inline-block mr-1">
			<label>
				<input type="checkbox" onChange="toggle_{{ widget.name }}('{{ widget.name }}')" class="update-checkbox">
				{{ widget.input_text }}
			</label>
		</div>
	<div class="input-update-{{ widget.name }}" style="display:none">
	{% else %}
	<div class="input-update-{{ widget.name }}">
	{% endif %}
		<input type="{{ widget.type }}" name="{{ widget.name }}" {% include "django/forms/widgets/attrs.html" %}>
	</div>
</div>

misc_tools/templates/misc_tools/direccion_form.html
{% load custom_tags %}
<script type="text/javascript" src="{{ STATIC_URL }}js/inputmask.js"></script>
{% if GOOGLE_API_KEY %}
<script src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_API_KEY }}"></script>
{% endif %}
<!--
    {{ dirForm.errors }}
-->
<div class="contenedor-direccion-{{ dirForm.prefix }}">
{{ dirForm.latitud.as_hidden }}
{{ dirForm.longitud.as_hidden }}
    <div class="row">
        <div class="col-md-12">
            {% if not ignorar_mensaje_geo and not GOOGLE_API_KEY %}
            <div class="alert alert-info alert-sm persist">
                Para habilitar la geolocalización es necesario especificar la <b>llave de acceso a los servicios de google</b> en configuración general. 
                <div><a href="/admin/configuracion/general/" target="_blank"><u>Click para ir la configuración</u></a></div>
            </div>
            {% endif %}

            {% if actualizar_ubicacion %}
                <input type="button"  value="Actualizar ubicación" class="btn btn-default text-right" style="display:none;" id="actualizar_ubicacion_mapa">
            {% endif %}
            <div id="mapContent" style="height:{{ map_content_height|default:'250px' }};display: none"></div>
        </div>

        <div class="col-md-5">
            <div class="form-group">
                 <label for="">Calle:</label>
                {{ dirForm.calle }}
                <div class="text-danger">{{ dirForm.calle.errors }}</div>
            </div>
        </div>

        <div class="col-md-2">
            <div class="form-group">
                 <label for="">Nº ext:</label>
                {{ dirForm.numero_e }}
                <div class="text-danger">{{ dirForm.numero_e.errors }}</div>
            </div>
        </div>

        <div class="col-md-2">
            <div class="form-group">
                 <label for="">Nº int:</label>
                {{ dirForm.numero_i }}
                <div class="text-danger">{{ dirForm.numero_i.errors }}</div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                 <label for="">Referencia</label>
                {{ dirForm.referencia }}
                <div class="text-danger">{{ dirForm.referencia.errors }}</div>
            </div>
        </div>

        <div class="col-md-2">
            <div class="form-group">
                 <label for="">CP:</label>
                {{ dirForm.cp }}
                <div class="text-danger">{{ dirForm.cp.errors }}</div>
            </div>
            <div style="display:none;">
                <div class="clickeable" id="close_colonias" style="position: absolute;z-index: 6;margin-top: -41px;right: 24px;">
                    <i class="fa fa-times text-danger" title="Cerrar"></i>
                </div>
                <div id="colonias"></div>
            </div>
            <div id="listadoColnias"></div>
        </div>

        <div class="col-md-5">
            <div class="form-group">
                {{ dirForm.colonia.label_tag }}
                {{ dirForm.colonia }}
                {{ dirForm.colonia.errors }}
            </div>
        </div>

        <div class="col-md-5">
            <div class="form-group">
                {{ dirForm.localidad.label_tag }}
                {{ dirForm.localidad }}
                {{ dirForm.localidad.errors }}
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                {{ dirForm.municipio.label_tag }}
                {{ dirForm.municipio }}
                {{ dirForm.municipio.errors }}
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                {{ dirForm.estado.label_tag }}
                {{ dirForm.estado }}
                {{ dirForm.estado.errors }}
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                {{ dirForm.pais_residencia.label_tag }}
                {{ dirForm.pais_residencia }} <span id="nombre_pais"></span>
                {{ dirForm.pais_residencia.errors }}
            </div>
        </div>

        {% if not ocultar_telefono %}
        <div class="col-md-6">
            <div class="form-group">
                {{ dirForm.telefono.label_tag }}
                {{ dirForm.telefono }}
                {{ dirForm.telefono.errors }}
            </div>
        </div>
        {% endif %} 

        {% if not ocultar_email and not agregar_empleado  %}
            <div class="col-md-6">
                <div class="form-group">
                    {{ dirForm.email.label_tag }}
                    {{ dirForm.email }}
                    {{ dirForm.email.errors }} <div id="estatuscorreo">&nbsp;</div>
                </div>
            </div>
        {% endif %}

    </div>
</div>

<script>

(function() {
var prefix = {% if dirForm.prefix %}"{{ dirForm.prefix }}-"{% else %} "" {% endif %}
var ubicaciones = [];
var $container = $(".contenedor-direccion-{{ dirForm.prefix }}")

$(function(){
    $("#id_"+prefix+"cp").change(cp);
    $("#id_"+prefix+"cp").on("focus",  cp);
    $("#close_colonias").on("click", function(){
        $container.find('#colonias').parent().hide();
    });
    $("#actualizar_ubicacion_mapa").on("click", actualizarMapa);

    {% if GOOGLE_API_KEY and dirForm.instance.latitud and dirForm.instance.longitud %}
        var geo = {
            lat: {{ dirForm.instance.latitud }}, 
            lng: {{ dirForm.instance.longitud }}
        };
        crearMapa(geo);
    {% endif %}
    
    {% if formato_telefono %}
        var phones = [{ "mask": "{{ formato_telefono }}" }, ];
        
        $("#id_"+prefix+"telefono").inputmask({ 
            mask: phones, 
            greedy: true, 
            definitions: { '#': { validator: "[0-9]", cardinality: 1}} 
        });
    {% endif %}

    {% if not ocultar_email and not agregar_empleado  %}
        $("#id_email").change(function(){

            validarEmail($("#id_email").val(), function(valido){
                if (valido){
                    var msg = "Correo válido.";
                    $("#estatuscorreo").html(msg).removeClass("text-danger").addClass("text-success");
                    $("#id_email").removeClass("bg-danger").addClass("bg-success");
                } else {
                    var msg = "Correo inválido, escriba un email real.";
                    $("#estatuscorreo").html(msg).removeClass("text-success").addClass("text-danger");
                    $("#id_email").removeClass("bg-success").addClass("bg-danger");
                }
            })
        });
    {% endif %}

    $('#id_'+prefix+'cp').attr('autocomplete', 'off');  
        var minLength_ac = minLength_ac || 1

        if ($().autocomplete) {
            $("#id_"+prefix+"pais_residencia").autocomplete({
                source:"/ajax/contains/pais_residencia/",
                minLength:minLength_ac,
                select:function(e,u){
                    $("#nombre_pais").html(u.item.label);
                },
            });
        }

        $.ajax({
            url:"/ajax/get_pais_residencia/?pais={{ dirForm.instance.pais_residencia }}",
            dataType:"json",
            success:function(data){

                if(data){
                  $("#nombre_pais").html(data.nombre);
                }
            },
        });

});

function cp(){
    var cp = $(this).val();
    
    if(cp == "" ){
        $container.find("#colonias").html("")
        return
    }
   
    $.getJSON('{% url "misc_tools:get_colonias" %}?cp=' + cp, function (datos){
        var col = "";
        
        if(datos.length > 1){

            for(var i=0; i<datos.length; i++){
                col += '<div> <a href="#" data-colonia="' + i +'">' + datos[i].colonia + '</a> </div>';
            }
            $container.find("#colonias").html(col);
            //$container.find('#colonias').show({effect:"slide", direction:"up", });
            $container.find("#colonias").parent().show();
            $container.find("#colonias a").click(function(e) {
                ubicacion($(this).attr("data-colonia"))
            })
        }
        
        ubicaciones = datos;
            
        if(datos.length == 1){
            $container.find("#colonias").html("")
            ubicacion(0);
        }
        
        if(datos.length < 1){
            $container.find("#colonias").html("")
        }   
        
    });
     
}

function ubicacion(i){
    $("#id_"+prefix+"colonia").val(ubicaciones[i].colonia);
    $("#id_"+prefix+"localidad").val(ubicaciones[i].localidad);
    $("#id_"+prefix+"municipio").val(ubicaciones[i].municipio);
    $("#id_"+prefix+"estado").val(ubicaciones[i].estado);
    $("#id_"+prefix+"pais_residencia").val("MX");
    $container.find('#colonias').parent().hide();
    {% if GOOGLE_API_KEY %}
    actualizarMapa();
    {% endif %}
}

function get_cp(){

    var colonia = $("#id_"+prefix+"colonia").val();
    var municipio = $("#id_"+prefix+"municipio").val();
    var localidad = $("#id_"+prefix+"localidad").val();
    var estado = $("#id_"+prefix+"estado").val();

    $.getJSON('/ubicaciones/get_cp/?colonia='+colonia+'&municipio='+municipio+'&localidad='+localidad+'&estado='+estado , function (datos){
        $("#id_"+prefix+"cp").val(datos.cp);
    });
}


function obtenerDireccion() {

    var calle = $('#id_'+prefix+'calle').val();
    var numero_e = $('#id_'+prefix+'numero_e').val();
    var numero_i = $('#id_'+prefix+'numero_i').val();
    var cp = $('#id_'+prefix+'cp').val();
    var colonia = $('#id_'+prefix+'colonia').val();
    var localidad = $('#id_'+prefix+'localidad').val();
    var estado = $('#id_'+prefix+'estado').val();

    var out = [
        calle,
        numero_e,
        colonia,
        cp,
        localidad + ',',
        estado
    ];

    return out.join(' ')

}

function actualizarLatLng(evento) {
    $('#id_'+prefix+'latitud').val(evento.latLng.lat().toFixed(6));
    $('#id_'+prefix+'longitud').val(evento.latLng.lng().toFixed(6));
}

function actualizarMapa() {
    var direccion = obtenerDireccion();
    var geocoder = new google.maps.Geocoder();

    geocoder.geocode({ 'address': direccion}, function(results, status) {
        if (status == google.maps.GeocoderStatus.OK) {
            var geo = {
                lat: results[0].geometry.location.lat(), 
                lng: results[0].geometry.location.lng()
            };
            crearMapa(geo, direccion, true);
        }
    }); 
}

function crearMapa(geo, title, setVal) {
    var $mapContainer = $container.find('#mapContent');
    $("#actualizar_ubicacion_mapa").show();
    //if (!$mapContainer.is(':visible')) {
    $mapContainer.slideDown('fast', function(){
        var map_settings = $.extend(window.googleMapDefault, {
            zoom: 14,
            center: geo
        });
        
        var map = new google.maps.Map($mapContainer[0], map_settings);

        var marker = new google.maps.Marker({
            position: geo,
            map: map,
            title: title,
            icon: window.getMapMarker(),
            draggable: true
        });

        google.maps.event.addListener(marker, 'dragend', actualizarLatLng);

        if (setVal) {
            $('#id_'+prefix+'latitud').val(geo.lat.toFixed(6));
            $('#id_'+prefix+'longitud').val(geo.lng.toFixed(6));
        }
    })
}

})();

</script>

misc_tools/templates/misc_tools/error_response.html
{% extends "http_error_base.html" %}

{% block title %}
Error
{% endblock title %}

{% block contenido %}
<div class="col-md-12 text-center">
	<div class="card card-body m-4">
		<h1 class="m-0"><i class="icon ion-md-close-circle-outline text-danger"></i></h1>
		<h2>Error</h2>
		<div class="lead">{{ errmsg }}</div>
		<hr>
		<p><a id="btnRegresar" class="btn btn-primary btn-lg" href="javascript:window.history.back()" role="button">Regresar</a></p>
	</div>
</div>
{% endblock contenido %}

misc_tools/templates/misc_tools/filtro_form.html
{% if not no_mostrar_buscar %}
<div class="align-bottom d-inline-block">
	Buscar:
	{{ filtro_form.q }} 
	{{ filtro_form.q.errors }}
</div>
{% endif %}

{% if not no_mostrar_elemento %}
<div class="align-bottom d-inline-block">
	Elem pag:
	{{ filtro_form.page_size }} 
	{{ filtro_form.page_size.errors }}
</div>
{% endif %}
<div class="align-bottom d-inline-block">
	<input id="btnBuscar" type="submit" value="Buscar" class="btn btn-primary">
	{% if request.GET.f %}
		<a href="{{ request.path }}" id="btnCerrar" class="btn btn-danger"><i class="icon ion-md-close"></i></a>
	{% endif %}
	<input type="hidden" value="1" name="f" />
	<input type="hidden" id="id_order" name="order" />
</div>

{% if exportar_excel or exportar_pdf %}
<div class="align-bottom d-inline-block filtro_exportar">
	<div id="btnClassMenu" class="btn-group" role="group">
    
    <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="icon ion-md-cloud-download"></i>
    </button>
	

    <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
    	{% if exportar_excel %}
      	<a class="dropdown-item" href="#" data-tipo="exportar_excel">Excel</a>
      	{% endif %}

      	{% if exportar_pdf %}
      	<a class="dropdown-item" href="#" data-tipo="exportar_pdf">PDF</a>
      	{% endif %}

    </div>
  </div>
</div>


{% endif %}

misc_tools/templates/misc_tools/paginado.html
{% load custom_tags %}
<div class="d-flex justify-content-between">
    <div>
        <div class="text-muted">
            <b>{{ objects_count }}</b> elementos
        </div>
    </div>
    
    <div>
        <nav class="text-right">
            <ul class="pagination m-0">
                {% if list.paginator.num_pages > 1 %}
                    {% if list.has_previous %}
                        <li class="page-item"><a class="page-link text-primary" data-toggle="tooltip" title="Primer página" href="{% append_to_get page=1 %}">&laquo;</a></li>
                        <li class="page-item"><a class="page-link text-primary" data-toggle="tooltip" title="Anterior" href="{% append_to_get page=list.previous_page_number %}"><span aria-hidden="true"><i class="icon ion-md-arrow-dropleft"></i></span></a></li>
                    {% endif %}
                    
                    {% for page in page_range %}
                        <li class="page-item {% if page == list.number %} active{% endif %}"><a class="page-link {% if page != list.number %} text-primary{% endif %}" href="{% append_to_get page=page %}">{{ page }}</a></li>
                    {% endfor %}

                    {% if list.has_next %}
                        <li class="page-item">
                            <a class="page-link text-primary" data-toggle="tooltip" title="Siguiente" href="{% append_to_get page=list.next_page_number %}"><span aria-hidden="true"><i class="icon ion-md-arrow-dropright"></i></span></a>
                        </li>
                        <li class="page-item"><a class="page-link text-primary" data-toggle="tooltip" title="Última página" href="{% append_to_get page=list.paginator.num_pages %}">&raquo;</a></li>
                     {% endif %}
                {% endif %}
            </ul>
        </nav>
    </div>
</div>

misc_tools/templates/misc_tools/success_response.html
{% extends "homedepot/clean_base.html" %}
{% load thumbnail %}

{% block _contenido %}
<div class="container-fluid">
    <div class="text-center">
        <div class="my-2">
            {% if configuracion.logo %}
            {% thumbnail configuracion.logo "x65" format="PNG" as im %}
                <img src="{{ im.url }}"  class="img-fluid">
            {% endthumbnail %}
            {% else %}
            <img src="https://placehold.it/120x60" class="img-fluid">
            {% endif %}
        </div>
    </div>
    <div class="text-center">
        <hr>
        <h1 class="text-success"><i class="icon ion-md-checkmark-circle-outline"></i></h1>
        <h3 class="text-success">{{ msg }}</h3>
        <button type="button" onclick="window.close();" class="btn btn-primary">Salir</button>
    </div>


</div>

{% endblock _contenido %}